name: learn-github-actions

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Make GET request
        run: |
          TARGET_URL="https://burc-yorumlari.vercel.app/get/aslan"
          RESPONSE=$(curl -sS "$TARGET_URL" | jq -r '.[0]')
          BURC=$(echo "$RESPONSE" | jq -r '.Burc')
          MOTTOSU=$(echo "$RESPONSE" | jq -r '.Mottosu')
          echo "Burc: $BURC ve MOTTOSU: $MOTTOSU"
